# Generated by Django 4.1.3 on 2022-11-16 17:19

from django.db import migrations


def populate_products(apps, schema_editor):
    product_model = apps.get_model('store', 'Product')

    # list of tuples of format (name, price, quantity_in_stock)
    product_data = [('Toothbrush', 11.05, 33),
                    ('Hairbrush', 1.10, 3),
                    ('Laptop', 2105.99, 55),
                    ]
                    
    for p in product_data:
        product_model(name=p[0], price=p[1], quantity_in_stock=p[2]).save()


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_products),
    ]
