version: "3.8"
services:
  database:
    container_name: database
    image: postgres:latest
    volumes:
      - type: volume
        source: app-data
        target: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=opply
      - POSTGRES_USER=opply
      # Password comes from a non version controlled .env file
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}      
  backend:
    build: .
    container_name: backend
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=opply
      - POSTGRES_USER=opply
      # Password comes from a non version controlled .env file
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}            
    depends_on:
      - database

volumes:
  app-data: